import type { Metadata } from "next";
import { Noto_Serif_Bengali} from "next/font/google";
import "./globals.css";



const noto_Serif_Bengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${noto_Serif_Bengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <main className="container mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
